foreground   #eac8bd
background   #101019
cursor       #eac8bd

color0       #101019
color8       #a38c84
color1       #C0717F
color9       #C0717F
color2       #B7836B
color10      #B7836B
color3       #EEA47D
color11      #EEA47D
color4       #C57787
color12      #C57787
color5       #689099
color13      #689099
color6       #EC8796
color14      #EC8796
color7       #eac8bd
color15      #eac8bd
