--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/isaac/Pictures/Wallpapers/neon.png"

-- Special
background="#101019"
foreground="#eac8bd"
cursor="#eac8bd"

-- Colors
color0="#101019"
color1="#C0717F"
color2="#B7836B"
color3="#EEA47D"
color4="#C57787"
color5="#689099"
color6="#EC8796"
color7="#eac8bd"
color8="#a38c84"
color9="#C0717F"
color10="#B7836B"
color11="#EEA47D"
color12="#C57787"
color13="#689099"
color14="#EC8796"
color15="#eac8bd"
