# Shell variables
# Generated by 'wal'
wallpaper='/home/isaac/Pictures/Wallpapers/neon.png'

# Special
background='#101019'
foreground='#eac8bd'
cursor='#eac8bd'

# Colors
color0='#101019'
color1='#C0717F'
color2='#B7836B'
color3='#EEA47D'
color4='#C57787'
color5='#689099'
color6='#EC8796'
color7='#eac8bd'
color8='#a38c84'
color9='#C0717F'
color10='#B7836B'
color11='#EEA47D'
color12='#C57787'
color13='#689099'
color14='#EC8796'
color15='#eac8bd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
